---
# Main github actions workflow
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Get vault
        run: curl -fSL https://releases.hashicorp.com/vault/1.13.3/vault_1.13.3_linux_amd64.zip | gunzip -> vault ; chmod u+x vault
      - name: Start vault
        run: ./vault server -dev -dev-root-token-id=test &
      - name: Get Consul
        run: curl -fSL https://releases.hashicorp.com/consul/1.15.3/consul_1.15.3_linux_amd64.zip | gunzip -> consul ; chmod u+x consul
      - name: Start consul dev server
        run: ./consul agent -dev &
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Init
        run: cd terraform ; terraform init
        env:
          VAULT_TOKEN: test
      - name: Validate
        run: cd terraform ; terraform validate
