---
# Main github actions workflow
name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Get vault
        run: curl -fSL https://releases.hashicorp.com/vault/1.13.3/vault_1.13.3_linux_amd64.zip | gunzip -> vault
      - name: Start vault
        run: vault server -dev -dev-root-token-id=test
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init
        run: cd terraform ; terraform init
        env:
          VAULT_TOKEN: test
      - name: Validate
        run: cd terraform ; terraform validate
