---
# Main github actions workflow
name: main
on:
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init
        run: cd terraform ; terraform init
      - name: Validate
        run: cd terraform ; terraform validate
